server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sgdevcamp2025/asyncgate
          # ToDo 테스트 후 변경
          default-label: be/feat/1-spring-cloud-init
          search-paths:
            - "config"

management:
  endpoints:
    web:
      exposure:
        include: health, refresh