server:
  port: 8000
  max-http-request-header-size: 64KB

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true

spring:
  application:
    name: apigateway-server
  cloud:
    gateway:
      routes:
        - id: swagger-ui
          uri: http://localhost:8000
          predicates:
            - Path=/swagger-ui/**, /v3/api-docs/**, /swagger-resources/**, /webjars/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: guild-server
          uri: lb://GUILD-SERVER
          predicates:
            - Path=/guilds/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/guilds/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
            - RemoveRequestHeader=X-Forwarded-For
            - RemoveRequestHeader=X-Forwarded-Proto
            - RemoveRequestHeader=X-Forwarded-Port
            - RemoveRequestHeader=Forwarded

        - id: user-server
          uri: lb://USER-SERVER
          predicates:
            - Path=/users/sign-up
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/users/(?<segment>.*), /$\{segment}

        - id: user-server
          uri: lb://USER-SERVER
          predicates:
            - Path=/users/sign-in
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/users/(?<segment>.*), /$\{segment}
        
        - id: user-server
          uri: lb://USER-SERVER
          predicates:
            - Path=/users/validation/authentication-code
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/users/(?<segment>.*), /$\{segment}

        - id: user-server
          uri: lb://USER-SERVER
          predicates:
            - Path=/users/validation/email
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/users/(?<segment>.*), /$\{segment}
          
        - id: user-server
          uri: lb://USER-SERVER
          predicates:
            - Path=/users/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/users/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
            

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, info

springdoc:
  api-docs:
    enabled: true
    version: openapi_3_0
  swagger-ui:
    config-url: /v3/api-docs/swagger-config
    operationsSorter: method
    urls:
      - name: Guild Service
        url: /guilds/v3/api-docs
      - name: User Service
        url: /users/v3/api-docs
  override-with-gateway-path: true
  show-actuator: true