server:
  port: 8000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true

spring:
  application:
    name: apigateway-server
  cloud:
    gateway:
      routes:
        - id: guild-server
          uri: lb://GUILD-SERVER
          predicates:
            - Path=/guilds/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/guilds/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

        - id: user-server
          uri: lb://USER-SERVER
          predicates:
            - Path=/users/sign-up
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/users/(?<segment>.*), /$\{segment}

        - id: user-server
          uri: lb://USER-SERVER
          predicates:
            - Path=/users/sign-in
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/users/(?<segment>.*), /$\{segment}
        
        - id: user-server
          uri: lb://USER-SERVER
          predicates:
            - Path=/users/validation/authentication-code
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/users/(?<segment>.*), /$\{segment}

        - id: user-server
          uri: lb://USER-SERVER
          predicates:
            - Path=/users/validation/email
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/users/(?<segment>.*), /$\{segment}
          
        - id: user-server
          uri: lb://USER-SERVER
          predicates:
            - Path=/users/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/users/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
            

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, info